UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

UI/Controllers/ManufacturerController.cs
using BLL;
using BOL;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UI.Controllers
{
    public class ManufacturerController : Controller
    {
        private IManufacturerBs objManufacturerBs;
        public ManufacturerController(IManufacturerBs _objManufacturerBs)
        {
            objManufacturerBs = _objManufacturerBs;
        }
        public IActionResult Index()
        {
            var list = objManufacturerBs.GetAll();
            return View(list);
        }

        [HttpGet]
        public IActionResult CreateOrEdit(int id)
        {
            Manufactureres obj = new Manufactureres();



            
            if (id > 0)
            {
                obj = objManufacturerBs.GetById(id);
            }

            return View(obj);
        }
        [HttpPost]
        public IActionResult CreateOrEdit(Manufactureres model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.ManufacturerId > 0) //update
                    {
                        objManufacturerBs.Update(model);
                    }
                    else //insert
                    {
                        objManufacturerBs.Insert(model);
                    }
                    TempData["SuccessMsg"] = "Record saved successfully.";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                //log
                TempData["ErrorMsg"] = "Error: " + ex.Message;
                return RedirectToAction(nameof(CreateOrEdit));
            }
           
        }


    }
}

UI/Controllers/ProductController.cs
using BLL;
using BOL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UI.Controllers
{
    public class ProductController : Controller
    {
        private IProductBs objProductBs;
        private IManufacturerBs objManufacturerBs;
        public ProductController(IProductBs _objProductBs, IManufacturerBs _objManufacturerBs)
        {
            objProductBs = _objProductBs;
            objManufacturerBs = _objManufacturerBs;
        }
        public IActionResult Index()
        {
            var list = objProductBs.GetAll();
            return View(list);
        }

        [HttpGet]
        public IActionResult CreateOrEdit(int id)
        {
            Products obj = new Products();

            ViewBag.ManufacturerList = new SelectList(objManufacturerBs.GetAll(), "ManufacturerId", "Name");

            if (id > 0)
            {
                obj = objProductBs.GetById(id);
            }

            return View(obj);
        }
        [HttpPost]
        public IActionResult CreateOrEdit(Products model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (model.ProductId > 0) //update
                    {
                        objProductBs.Update(model);
                    }
                    else //insert
                    {
                        objProductBs.Insert(model);
                    }
                    TempData["SuccessMsg"] = "Record saved successfully.";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                //log
                TempData["ErrorMsg"] = "Error: " + ex.Message;
                return RedirectToAction(nameof(CreateOrEdit));
            }

        }
    }
}

UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Home Page</h1>

UI/Views/Manufacturer/CreateOrEdit.cshtml
@model BOL.Manufactureres

@{
    ViewData["Title"] = "CreateOrEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Manufactureres</h4>
@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Error!</strong><br />
        <p>@TempData["ErrorMsg"].ToString()</p>
    </div>
}
@if (TempData["SuccessMsg"] != null)
{
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Success!</strong><br />
        <p>@TempData["SuccessMsg"].ToString()</p>
    </div>
}

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateOrEdit">

            <input type="hidden" asp-for="ManufacturerId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

UI/Views/Manufacturer/Index.cshtml
@model IEnumerable<BOL.Manufactureres>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Manufacturer List</h1>
@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Error!</strong><br />
        <p>@TempData["ErrorMsg"].ToString()</p>
    </div>
}
@if (TempData["SuccessMsg"] != null)
{
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Success!</strong><br />
        <p>@TempData["SuccessMsg"].ToString()</p>
    </div>
}
    <p>
        <a asp-action="CreateOrEdit">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.State)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ZipCode)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.State)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ZipCode)
                    </td>
                    <td>
                        <a asp-action="CreateOrEdit" asp-route-id="@item.ManufacturerId">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

UI/Views/Product/CreateOrEdit.cshtml
@model BOL.Products

@{
    ViewData["Title"] = "CreateOrEdit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Products</h4>
@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Error!</strong><br />
        <p>@TempData["ErrorMsg"].ToString()</p>
    </div>
}
@if (TempData["SuccessMsg"] != null)
{
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Success!</strong><br />
        <p>@TempData["SuccessMsg"].ToString()</p>
    </div>
}

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateOrEdit">

          
            <input type="hidden" asp-for="ProductId" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Manufacturer</label>
                <select asp-for="ManufacturerId" class="form-control" asp-items="ViewBag.ManufacturerList">
                   <option>--Select--</option>  
                </select>
                <span asp-validation-for="ManufacturerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

UI/Views/Product/Index.cshtml
@model IEnumerable<BOL.Products>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Products List</h1>
@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-dismissible alert-danger">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Error!</strong><br />
        <p>@TempData["ErrorMsg"].ToString()</p>
    </div>
}
@if (TempData["SuccessMsg"] != null)
{
    <div class="alert alert-dismissible alert-success">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Success!</strong><br />
        <p>@TempData["SuccessMsg"].ToString()</p>
    </div>
}
    <p>
        <a asp-action="CreateOrEdit">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Manufactureres)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Manufactureres.Name)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--CSS-->
    <link href="~/bootswatch/united/bootstrap.min.css" rel="stylesheet" />
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" />

    <!--Js-->
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">PRS</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">
                            Home
                            <span class="visually-hidden">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Manufacturer" asp-action="Index">Manufacturer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Product" asp-action="Index">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Recalls</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Announcements</a>
                    </li>
                </ul>
                
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        @RenderBody()
    </div>
</body>
</html>